	1	-nasal
Z	3	+voice, +aper1+, -ant
O	2	+LAB, -bk2+
s	3	+ant, -voice, +strid
z	3	+ant, +voice, +strid
a	2	-hi1+, +bk1+
U	3	-hi1+, +LAB, -tense
u	3	-hi1+, +LAB, +tense
ç	3	+hi1+, +LAB, -tense
Q	2	-hi2+, -bk2+
A	3	-bk1+, -hi2+, +bk2+
N	2	+nasal, +DORS
j	2	-syl, -bk2+
w	2	-syl, +bk2+
m	2	+nasal, +LAB
’	2	+syl, +COR
h	2	-sonority2+, +aper2+
n	2	+nasal, +COR
I	3	-bk2+, -hi1+, -tense
i	3	-bk2+, -hi1+, +tense
E	3	-bk2+, +hi1+, -tense
W	2	+bk2+, +diph
o	4	+tense, +hi1+, +LAB, -diph
l	1	+lat
e	4	+tense, -bk2+, +hi1+, -diph
p	3	-voice, -sonority1+, +LAB
k	2	-voice, +DORS
C	3	-voice, -sonority1+, -ant
t	3	-voice, -sonority1+, +ant
f	3	-voice, +sonority1+, +LAB
S	3	-voice, +sonority1+, -ant
b	3	+voice, -sonority1+, +LAB
J	3	+voice, -sonority1+, -ant
d	3	+voice, -sonority1+, +ant
g	3	+voice, -sonority1+, +DORS
r	3	+sonority2+, -syl, -ant
v	3	+voice, +aper1+, +LAB
OW	2	+LAB, +diph
lr	3	+sonority3+, -syl, +COR
JZ	3	+voice, -sonority2+, -ant
Uç	2	+LAB, -tense
Ii	4	+hi2+, -hi1+, +syl, -bk2+
IU	3	+hi2+, -hi1+, -tense
Ss	3	-voice, +sonority1+, +strid
Dz	3	+voice, +aper1+, +ant
Aa	2	-hi2+, +bk2+
bp	2	-sonority1+, +LAB
AQ	2	-hi2+, -bk1+
oç	3	+hi1+, +LAB, -diph
mw	3	+sonority2+, -syl, +LAB
CJ	2	-sonority1+, -ant
dt	2	-sonority1+, +ant
gk	2	-sonority1+, +DORS
ln	2	+sonority2+, +ant
ei	3	+tense, -bk2+, -diph
´’	2	+hi1+, +bk1+
eo	3	+tense, +hi1+, -diph
ou	3	+tense, +LAB, -diph
Wo	3	+bk2+, +hi1+, +tense
ç√	3	+bk2+, +hi1+, -tense
Ua	3	+bk2+, -hi1+, -tense
Ts	3	-voice, +sonority1+, +ant
fv	2	+aper1+, +LAB
r’	2	+sonority2+, -ant
Ee	3	-bk2+, +hi1+, -diph
dn	4	+voice, -aper1+, -sonority3+, +ant
iu	2	-hi1+, +tense
mv	4	+voice, -sonority3+, +sonority1+, +LAB
fp	2	-voice, +LAB
Ct	3	-voice, -sonority1+, +COR
Jd	3	+voice, -sonority1+, +COR
Ng	3	+voice, -sonority3+, +DORS
bm	4	+voice, -aper1+, -sonority3+, +LAB
OY	2	-bk2+, +diph
EI	2	-bk2+, -tense
Jr	4	+voice, -aper1+, -syl, -ant
CS	2	-voice, -ant
Zz	3	+voice, +sonority1+, +strid
sz	2	+ant, +strid
SZ	2	+aper1+, -ant
Zr	4	+voice, +sonority1+, -syl, -ant
bv	3	+voice, -sonority2+, +LAB
jw	2	-syl, -hi1+
hl	2	-sonority4+, +aper2+
Uu	3	+LAB, +syl, -hi1+
STs	3	-voice, +sonority1+, +COR
OYe	3	-bk2+, +hi1+, +tense
AUu	4	-bk1+, -hi1+, +syl, +bk2+
Wou	2	+bk2+, +tense
Iij	3	+hi2+, -hi1+, -bk2+
Uç√	3	+bk2+, +hi2+, -tense
JZr	3	+voice, -syl, -ant
OWo	3	+hi1+, +LAB, +tense
Woç	3	+hi1+, +LAB, +bk2+
Nmn	1	+nasal
oç√	4	+bk2+, -bk1+, +hi1+, -diph
Eç√	2	+hi1+, -tense
AQa	1	-hi2+
IQi	3	-hi1+, +syl, -bk2+
a´’	1	+bk1+
IUa	2	-hi1+, -tense
OWY	1	+diph
JZz	2	+voice, +strid
jrw	2	-syl, +sonority4+
CJr	3	-aper1+, -syl, -ant
Uuw	2	+LAB, -hi1+
Jdn	4	+voice, -aper1+, -sonority3+, +COR
bmp	3	-aper1+, -sonority3+, +LAB
Njw	2	+sonority1+, +DORS
bmw	4	+voice, -aper1+, -syl, +LAB
dln	3	+voice, -aper1+, +ant
Jr’	3	+voice, -aper1+, -ant
SZr	3	+sonority1+, -syl, -ant
Dnz	4	+voice, -sonority3+, +sonority1+, +ant
dnt	3	-aper1+, -sonority3+, +ant
lnr	3	+sonority2+, -syl, +COR
bmv	3	+voice, -sonority3+, +LAB
DZz	3	+voice, +aper1+, +COR
Ngk	2	-sonority3+, +DORS
fmv	3	-sonority3+, +sonority1+, +LAB
Ddz	3	+voice, -sonority2+, +ant
lr’	2	+sonority3+, +COR
mvw	4	+voice, +sonority1+, -syl, +LAB
Zr’	3	+voice, +sonority1+, -ant
Tst	2	-voice, +ant
CSs	2	-voice, +strid
OWou	2	+LAB, +tense
Woç√	3	-bk1+, +hi1+, +bk2+
AUuw	3	-bk1+, -hi1+, +bk2+
DZvz	2	+aper1+, +voice
Uouç	2	+LAB, -diph
CJdt	2	-sonority1+, +COR
fmvw	3	+sonority1+, -syl, +LAB
Ddnz	3	+voice, -sonority3+, +ant
DZnz	4	+voice, -sonority3+, +sonority1+, +COR
SZr’	2	+sonority1+, -ant
Jbdg	2	-sonority1+, +voice
bfpv	2	-sonority2+, +LAB
SZsz	2	+sonority1+, +strid
Nhmn	3	-sonority3+, +sonority1+, -aper1+
Ckpt	2	-sonority1+, -voice
CJSZ	2	-sonority2+, -ant
STfs	2	+aper1+, -voice
Dlnz	3	+voice, +sonority1+, +ant
JZr’	2	+voice, -ant
CJr’	2	-aper1+, -ant
dlnt	2	-aper1+, +ant
DTsz	2	+aper1+, +ant
jlrw	2	-syl, +sonority3+
OYei	2	-bk2+, +tense
IQij	2	-hi1+, -bk2+
Nlmn	2	+sonority2+, -sonority4+
IUiu	3	-hi1+, +syl, +hi2+
EIei	3	-bk2+, +hi2+, -diph
Uaç√	2	+bk2+, -tense
lnr’	2	+sonority2+, +COR
AUau	3	-hi1+, +syl, +bk2+
Ngjw	2	+voice, +DORS
bmpw	3	-aper1+, -syl, +LAB
Jdln	4	+voice, -aper1+, -sonority4+, +COR
OWoç	2	+LAB, +hi1+
eiou	2	+tense, -diph
bmvw	3	+voice, -syl, +LAB
EOYe	2	+hi1+, -bk2+
EIQei	2	-bk2+, -diph
Ddlnz	2	+voice, +ant
DJZdz	3	+voice, -sonority2+, +COR
CJSZr	2	-syl, -ant
AUauw	2	-hi1+, +bk2+
STfhs	2	+sonority1+, -voice
UWouç	3	+LAB, +syl, +bk2+
Nhlmn	3	-sonority4+, +sonority1+, -aper1+
hjlrw	2	-syl, +aper2+
Chkpt	2	-aper1+, -voice
DZlnz	4	+voice, -sonority4+, +sonority1+, +COR
Jdlnr	4	+voice, -aper1+, -syl, +COR
Ngjkw	1	+DORS
Eeoç√	3	-bk1+, +hi1+, -diph
oç´√’	3	+bk2+, +hi1+, -diph
EIUç√	2	+hi2+, -tense
OWYeo	2	+hi1+, +tense
Uouç√	4	+bk2+, -bk1+, +hi2+, -diph
bfmpv	2	-sonority3+, +LAB
CJdnt	3	-aper1+, -sonority3+, +COR
CSTst	2	-voice, +COR
DTnsz	3	-sonority3+, +sonority1+, +ant
DSTZsz	2	+aper1+, +COR
CJdlnt	3	-aper1+, -sonority4+, +COR
DZlnrz	4	+voice, +sonority1+, -syl, +COR
DJZdnz	3	+voice, -sonority3+, +COR
Jdlnr’	3	+voice, -aper1+, +COR
UWouwç	2	+LAB, +bk2+
IUijuw	2	-hi1+, +hi2+
AIQUiu	3	-hi1+, +syl, -bk1+
Woç´√’	2	+hi1+, +bk2+
EIOYei	3	+hi2+, +syl, -bk2+
CJSZr’	1	-ant
UWouç√	4	-bk1+, +hi2+, +syl, +bk2+
AUouç√	3	+bk2+, -bk1+, -diph
CJSZsz	1	+strid
EIUaç√	1	-tense
bfmpvw	2	-syl, +LAB
OUWouç	2	+syl, +LAB
DTlnsz	2	+sonority1+, +ant
DTdstz	2	-sonority2+, +ant
OUWouwç	2	+sonority3+, +LAB
CJdlnrt	3	-aper1+, -syl, +COR
AIQUaiu	2	+syl, -hi1+
EIOYeij	2	+hi2+, -bk2+
Eeoç´√’	2	+hi1+, -diph
EIOQYei	2	+syl, -bk2+
AUWouç√	3	-bk1+, +syl, +bk2+
UWouwç√	3	-bk1+, +hi2+, +bk2+
DZlnrz’	3	+voice, +sonority1+, +COR
Njlmnrw	2	-syl, +sonority2+
DJZdlnz	3	+voice, -sonority4+, +COR
Uouç´√’	3	+bk2+, +hi2+, -diph
OWYeiou	1	+tense
JNbdgmn	3	-aper1+, -sonority3+, +voice
DTdnstz	2	-sonority3+, +ant
DNZmnvz	3	-sonority3+, +sonority1+, +voice
DSTZnsz	3	-sonority3+, +sonority1+, +COR
CSTfkpst	2	-aper2+, -voice
JNbdglmn	3	-aper1+, -sonority4+, +voice
DNZlmnvz	3	-sonority4+, +sonority1+, +voice
AIQUijuw	2	-hi1+, -bk1+
DSTZlnsz	3	-sonority4+, +sonority1+, +COR
DJZbdgvz	2	-sonority2+, +voice
DJZdlnrz	3	+voice, -syl, +COR
OUWmouwç	2	+sonority2+, +LAB
EIOQYeij	1	-bk2+
DSTZfsvz	1	+aper1+
CJdlnrt’	2	-aper1+, +COR
CJbdgkpt	1	-sonority1+
AUWouwç√	2	-bk1+, +bk2+
UWouç´√’	3	+hi2+, +syl, +bk2+
DTdlnstz	1	+ant
EOWYeoç√	2	+hi1+, -bk1+
Nhjlmnrw	3	+sonority1+, -syl, -aper1+
OUWmouvwç	3	+voice, +sonority1+, +LAB
AIQUaijuw	1	-hi1+
CSTfhkpst	1	-voice
UWouwç´√’	2	+hi2+, +bk2+
EIUeiouç√	3	-bk1+, +hi2+, -diph
AUaouç´√’	2	+bk2+, -diph
CJbdghkpt	2	-sonority2+, -aper1+
DSTZfhsvz	2	+sonority1+, -sonority2+
DJZdlnrz’	2	+voice, +COR
OUWbmouwç	3	+voice, -aper1+, +LAB
DSTZlnrsz	3	+sonority1+, -syl, +COR
DSTZlnrsz’	2	+sonority1+, +COR
OUWfmouvwç	2	+sonority1+, +LAB
CDJSTZdstz	2	-sonority2+, +COR
AUWaouç´√’	2	+syl, +bk2+
OUWbmouvwç	2	+voice, +LAB
EOWYeoç´√’	1	+hi1+
OUWbmopuwç	2	-aper1+, +LAB
CJNbdgkmnpt	2	-aper1+, -aper2+
DJNZbdgmnvz	2	-sonority3+, +voice
CDJSTZdnstz	2	-sonority3+, +COR
DNSTZfmnsvz	2	+sonority1+, -aper2+
AUWaouwç´√’	1	+bk2+
EIUeiouç´√’	2	+hi2+, -diph
AEIQUeiouç√	2	-bk1+, -diph
DNZjlmnrvwz	3	+sonority1+, -syl, +voice
JNbdgjlmnrw	3	-aper1+, -syl, +voice
OUWbfmopuvwç	1	+LAB
CJNbdghkmnpt	2	-sonority3+, -aper1+
EIOUWYeiouç√	3	+hi2+, +syl, -bk1+
DNSTZfhmnsvz	2	+sonority1+, -sonority3+
CDJSTZdlnstz	2	-sonority4+, +COR
DJNZbdglmnvz	2	-sonority4+, +voice
CJNbdghklmnpt	2	-sonority4+, -aper1+
CDJSTZdlnrstz	2	-syl, +COR
DNSTZfhlmnsvz	2	+sonority1+, -sonority4+
AEIOQUWYeiouç√	2	+syl, -bk1+
EIOUWYeiouç´√’	2	+syl, +hi2+
EIOUWYeijouwç√	2	+hi2+, -bk1+
CDJSTZdlnrstz’	1	+COR
AEIQUaeiouç´√’	1	-diph
DJNZbdgjlmnrvwz	2	-syl, +voice
EIOUWYeijouwç´√’	1	+hi2+
AEIOQUWYeijouwç√	1	-bk1+
CDJSTZbdfgkpstvz	2	-sonority2+, -aper2+
DNSTZfhjlmnrsvwz	2	-syl, +sonority1+
CJNbdghjklmnprtw	2	-syl, -aper1+
CDJSTZbdfghkpstvz	1	-sonority2+
AEIOQUWYaeiouç´√’	1	+syl
CDJNSTZbdfgkmnpstvz	1	-aper2+
CDJNSTZbdfghkmnpstvz	1	-sonority3+
AEIOQUWYaeijoruwç´√’	1	+sonority4+
CDJNSTZbdfghklmnpstvz	1	-sonority4+
AEIOQUWYaeijloruwç´√’	1	+sonority3+
AEIOQUWYaehijloruwç´√’	1	+aper2+
CDJNSTZbdfghjklmnprstvwz	1	-syl
AEINOQUWYaeijlmnoruwç´√’	1	+sonority2+
AEINOQUWYaehijlmnoruwç´√’	2	+sonority1+, -aper1+
ADEINOQUWYZaeijlmnoruvwzç´√’	2	+sonority1+, +voice
AEIJNOQUWYabdegijlmnoruwç´√’	2	-aper1+, +voice
ADEIJNOQUWYZabdegijlmnoruvwzç´√’	1	+voice
ADEINOQSTUWYZaefhijlmnorsuvwzç´√’	1	+sonority1+
ACEIJNOQUWYabdeghijklmnoprtuwç´√’	1	-aper1+
ACDEIJNOQSTUWYZabdefghijklmnoprstuvwzç´√’	0	+seg
