	1	-labial
@	1	+reduced
l	1	+lateral
r	1	+rhotic
h	1	+spread glottis
w	2	-consonantal, +labial
j	2	-consonantal, +coronal
4	2	-bk, +rnd
8	3	-bk, -hi, +rhotacized
I	3	-bk, +hi, -long
7	3	-bk, +hi, +rhotacized
0	3	-bk, +lo, +long
{	3	-bk, +lo, -nasal
6	2	+bk, +diphthong
3	3	+bk, -hi, +rhotacized
U	2	+rnd, -long
9	2	+rnd, +rhotacized
V	4	+bk, -lo, -hi, -long
Q	3	+bk, +lo, -long
2	3	-rnd, -bk, +diphthong
c	2	-long, +nasal
E	5	-long, -bk, -lo, -hi, -reduced
#	3	+long, +lo, -nasal
i	4	+long, -bk, +hi, -rhotacized
u	4	+long, +bk, +hi, -rhotacized
1	6	-diphthong, +long, -bk, -lo, -hi, -rhotacized
m	2	+labial, +nasal
n	2	+coronal, +nasal
N	2	+dorsal, +sonorant
k	2	+dorsal, +voiceless
p	2	+bilabial, +voiceless
v	3	+dental, +labial, +voice
f	3	+dental, +labial, +voiceless
D	3	+dental, +coronal, +voice
T	3	+dental, +coronal, +voiceless
g	3	+obstruent, +dorsal, +voice
b	3	+obstruent, +bilabial, +voice
t	3	+stop, +alveolar, +voiceless
_	2	+affricate, +voice
J	2	+affricate, +voiceless
d	3	+oral, +coronal, +voice
z	3	+continuant, +alveolar, +voice
s	3	+continuant, +alveolar, +voiceless
Z	3	+continuant, +palatal, +voice
S	3	+continuant, +palatal, +voiceless
jw	1	+glide
J_	1	+affricate
38	2	-hi, +rhotacized
IU	2	+hi, -long
79	2	+hi, +rhotacized
24	2	-bk, +diphthong
78	2	-bk, +rhotacized
0c	2	-bk, +nasal
7i	3	-bk, +hi, +long
Ii	3	-bk, +hi, -rhotacized
@E	4	-bk, -lo, -hi, -long
c{	3	-bk, +lo, -long
39	2	+bk, +rhotacized
q~	2	+bk, +nasal
$5	3	+bk, -hi, +rnd
QV	3	+bk, -hi, -long
9u	3	+bk, +hi, +long
Uu	3	+bk, +hi, -rhotacized
UV	3	+bk, -lo, -long
#Q	3	+bk, +lo, -nasal
26	2	-rnd, +diphthong
36	4	-rnd, +bk, -lo, +long
3V	4	-rnd, +bk, -lo, -diphthong
6V	4	-rnd, +bk, -lo, -rhotacized
EV	4	-long, -lo, -hi, -reduced
Q{	3	-long, +lo, -nasal
EI	4	-long, -bk, -lo, -reduced
iu	3	+long, +hi, -rhotacized
18	5	+long, -bk, -lo, -hi, -diphthong
12	6	+long, -rnd, -bk, -lo, -hi, -rhotacized
01	5	-diphthong, +long, -bk, -hi, -rhotacized
1i	5	-diphthong, +long, -bk, -lo, -rhotacized
#3	5	-diphthong, +long, -rnd, +bk, -nasal
E{	5	-reduced, -long, -bk, -hi, -nasal
1E	6	-reduced, -diphthong, -bk, -lo, -hi, -rhotacized
#6	5	-rhotacized, +long, -rnd, +bk, -nasal
#1	6	-rhotacized, -diphthong, +long, -rnd, -hi, -nasal
fv	2	+labial, +dental
mr	2	+labial, +consonantal
bp	2	+labial, +oral
fp	2	+labial, +voiceless
DT	2	+coronal, +dental
dt	2	+coronal, +oral
gk	2	+dorsal, +obstruent
Ng	2	+dorsal, +voice
Dv	2	+dental, +voice
Tf	2	+dental, +voiceless
sz	2	+alveolar, +continuant
st	2	+alveolar, +voiceless
SZ	2	+palatal, +continuant
Z_	2	+palatal, +voice
JS	2	+palatal, +voiceless
bv	3	+obstruent, +labial, +voice
dz	3	+obstruent, +alveolar, +voice
bm	3	+stop, +labial, +voice
Jt	3	+stop, +coronal, +voiceless
dn	3	+stop, +alveolar, +voice
_d	4	+stop, +obstruent, +coronal, +voice
Zz	3	+strident, +continuant, +voice
Ss	3	+strident, +continuant, +voiceless
246	1	+diphthong
Ngk	1	+dorsal
Nmn	1	+nasal
$45	2	-hi, +rnd
7Ii	2	+hi, -bk
9Uu	2	+hi, +bk
@EV	3	-lo, -hi, -long
0c{	2	+lo, -bk
Qc{	2	+lo, -long
#Q{	2	+lo, -nasal
@EI	3	-bk, -lo, -long
QUV	2	+bk, -long
36V	3	+bk, -lo, -rnd
#q~	3	+bk, +lo, +long
378	2	-rnd, +rhotacized
128	5	-rnd, -bk, -lo, -hi, +long
Ec{	4	-long, -bk, -hi, -reduced
@E{	4	-long, -bk, -hi, -nasal
EIV	4	-long, -rnd, -lo, -reduced
0q~	2	+long, +nasal
018	4	+long, -bk, -hi, -diphthong
124	5	+long, -bk, -lo, -hi, -rhotacized
$35	5	+long, +bk, -lo, -hi, -diphthong
$56	5	+long, +bk, -lo, -hi, -rhotacized
138	5	+long, -rnd, -lo, -hi, -diphthong
126	5	+long, -rnd, -lo, -hi, -rhotacized
012	5	+long, -rnd, -bk, -hi, -rhotacized
12i	5	+long, -rnd, -bk, -lo, -rhotacized
#36	4	+long, -rnd, +bk, -nasal
$5u	4	+long, +rnd, +bk, -rhotacized
18E	5	-diphthong, -bk, -lo, -hi, -reduced
1@E	5	-diphthong, -bk, -lo, -hi, -rhotacized
$5V	5	-diphthong, +bk, -lo, -hi, -rhotacized
$15	5	-diphthong, +long, -lo, -hi, -rhotacized
01i	4	-diphthong, +long, -bk, -rhotacized
12E	6	-reduced, -rnd, -bk, -lo, -hi, -rhotacized
EI{	4	-reduced, -long, -bk, -nasal
1EV	6	-reduced, -diphthong, -rnd, -lo, -hi, -rhotacized
#QV	5	-rhotacized, -diphthong, -rnd, +bk, -nasal
#$5	6	-rhotacized, -diphthong, +long, +bk, -hi, -nasal
#1i	5	-rhotacized, -diphthong, +long, -rnd, -nasal
1E{	6	-rhotacized, -reduced, -diphthong, -bk, -hi, -nasal
mrw	2	+labial, +sonorant
bmp	2	+labial, +stop
lnr	2	+coronal, +consonantal
bmr	3	+bilabial, +consonantal, +voice
dnt	2	+alveolar, +stop
_dn	3	+stop, +coronal, +voice
DZz	3	+continuant, +coronal, +voice
STs	3	+continuant, +coronal, +voiceless
bdg	2	+oral, +voice
kpt	2	+oral, +voiceless
Z_z	2	+strident, +voice
JSs	2	+strident, +voiceless
Tfh	2	+distributed, +voiceless
3789	1	+rhotacized
0cq~	1	+nasal
DTfv	1	+dental
JSZ_	1	+palatal
bmpr	2	+consonantal, +bilabial
79iu	2	+hi, +long
IUiu	2	+hi, -rhotacized
#Qq~	2	+lo, +bk
#0q~	2	+lo, +long
@Ec{	3	-bk, -hi, -long
1248	4	-bk, -lo, -hi, +long
18@E	4	-bk, -lo, -hi, -diphthong
$356	4	+bk, -lo, -hi, +long
$35V	4	+bk, -lo, -hi, -diphthong
$56V	4	+bk, -lo, -hi, -rhotacized
@EIV	3	-rnd, -lo, -long
0128	4	-rnd, -bk, -hi, +long
128E	5	-rnd, -bk, -lo, -hi, -reduced
12@E	5	-rnd, -bk, -lo, -hi, -rhotacized
$59u	3	+rnd, +bk, +long
$5Uu	3	+rnd, +bk, -rhotacized
EIUV	3	-long, -lo, -reduced
EIc{	3	-long, -bk, -reduced
@EI{	3	-long, -bk, -nasal
0124	4	+long, -bk, -hi, -rhotacized
178i	4	+long, -bk, -lo, -diphthong
124i	4	+long, -bk, -lo, -rhotacized
$56u	4	+long, +bk, -lo, -rhotacized
126i	4	+long, -rnd, -lo, -rhotacized
012i	4	+long, -rnd, -bk, -rhotacized
#3q~	4	+long, -rnd, +bk, -diphthong
#6q~	4	+long, -rnd, +bk, -rhotacized
$45u	3	+long, +rnd, -rhotacized
1@EV	5	-diphthong, -rnd, -lo, -hi, -rhotacized
#3QV	4	-diphthong, -rnd, +bk, -nasal
#$35	5	-diphthong, +long, +bk, -hi, -nasal
#138	5	-diphthong, +long, -rnd, -hi, -nasal
124E	5	-reduced, -bk, -lo, -hi, -rhotacized
EQV{	4	-reduced, -long, -hi, -nasal
18E{	5	-reduced, -diphthong, -bk, -hi, -nasal
1EIi	5	-reduced, -diphthong, -bk, -lo, -rhotacized
#6QV	4	-rhotacized, -rnd, +bk, -nasal
#$56	5	-rhotacized, +long, +bk, -hi, -nasal
#126	5	-rhotacized, +long, -rnd, -hi, -nasal
1@E{	5	-rhotacized, -diphthong, -bk, -hi, -nasal
#$15	5	-rhotacized, -diphthong, +long, -hi, -nasal
#$5u	5	-rhotacized, -diphthong, +long, +bk, -nasal
12E{	6	-rhotacized, -reduced, -rnd, -bk, -hi, -nasal
bfpv	2	+labial, +obstruent
bmrv	3	+labial, +consonantal, +voice
jlnr	2	+coronal, +sonorant
bmrw	2	+bilabial, +voice
dstz	2	+alveolar, +obstruent
J_dt	3	+obstruent, +coronal, +stop
Jkpt	2	+stop, +voiceless
_bdg	3	+stop, +obstruent, +voice
SZsz	2	+continuant, +strident
DZvz	2	+continuant, +voice
bmprw	1	+bilabial
Nlmnr	1	+consonantal
DTfhv	1	+distributed
@EIUV	2	-lo, -long
$356V	3	-lo, -hi, +bk
@EIc{	2	-bk, -long
01248	3	-bk, -hi, +long
128@E	4	-bk, -lo, -hi, -rnd
1248E	4	-bk, -lo, -hi, -reduced
124@E	4	-bk, -lo, -hi, -rhotacized
$59Uu	2	+bk, +rnd
12368	4	-rnd, -lo, -hi, +long
1278i	4	-rnd, -bk, -lo, +long
#36q~	3	-rnd, +bk, +long
#36QV	3	-rnd, +bk, -nasal
$459u	2	+rnd, +long
$45Uu	2	+rnd, -rhotacized
EQVc{	3	-long, -hi, -reduced
@EQV{	3	-long, -hi, -nasal
$1358	4	+long, -lo, -hi, -diphthong
0178i	3	+long, -bk, -diphthong
0124i	3	+long, -bk, -rhotacized
#$356	4	+long, +bk, -hi, -nasal
$359u	4	+long, +bk, -lo, -diphthong
1378i	4	+long, -rnd, -lo, -diphthong
18@E{	4	-diphthong, -bk, -hi, -nasal
1@EIi	4	-diphthong, -bk, -lo, -rhotacized
$5UVu	4	-diphthong, +bk, -lo, -rhotacized
138EV	5	-diphthong, -rnd, -lo, -hi, -reduced
#QVq~	4	-diphthong, -rnd, +bk, -rhotacized
$15iu	4	-diphthong, +long, -lo, -rhotacized
#$5q~	5	-diphthong, +long, +bk, -hi, -rhotacized
#01q~	5	-diphthong, +long, -rnd, -hi, -rhotacized
126EV	5	-reduced, -rnd, -lo, -hi, -rhotacized
128E{	5	-reduced, -rnd, -bk, -hi, -nasal
12EIi	5	-reduced, -rnd, -bk, -lo, -rhotacized
EIQV{	4	-reduced, -long, -rnd, -nasal
$15EV	5	-reduced, -diphthong, -lo, -hi, -rhotacized
01Ec{	5	-reduced, -diphthong, -bk, -hi, -rhotacized
1EIVi	5	-reduced, -diphthong, -rnd, -lo, -rhotacized
12@E{	5	-rhotacized, -rnd, -bk, -hi, -nasal
#$56u	4	-rhotacized, +long, +bk, -nasal
#126i	4	-rhotacized, +long, -rnd, -nasal
#$5QV	5	-rhotacized, -diphthong, +bk, -hi, -nasal
124E{	5	-rhotacized, -reduced, -bk, -hi, -nasal
1EIi{	5	-rhotacized, -reduced, -diphthong, -bk, -nasal
bmrvw	2	+labial, +voice
J_dnt	2	+coronal, +stop
JSTst	2	+coronal, +voiceless
dlnrz	2	+alveolar, +voice
DZ_dz	3	+obstruent, +coronal, +voice
STfhs	2	+continuant, +voiceless
79IUiu	1	+hi
$459Uu	1	+rnd
bdgkpt	1	+oral
JSZ_sz	1	+strident
bfmprv	2	+consonantal, +labial
@EQVc{	2	-hi, -long
1248@E	3	-lo, -hi, -bk
12478i	3	-bk, -lo, +long
$3569u	3	+bk, -lo, +long
$56UVu	3	+bk, -lo, -rhotacized
138@EV	4	-rnd, -lo, -hi, -diphthong
126@EV	4	-rnd, -lo, -hi, -rhotacized
01278i	3	-rnd, -bk, +long
128@E{	4	-rnd, -bk, -hi, -nasal
12@EIi	4	-rnd, -bk, -lo, -rhotacized
#3QVq~	3	-rnd, +bk, -diphthong
#6QVq~	3	-rnd, +bk, -rhotacized
EIQVc{	3	-long, -rnd, -reduced
@EIQV{	3	-long, -rnd, -nasal
$12456	4	+long, -lo, -hi, -rhotacized
#$35q~	4	+long, +bk, -hi, -diphthong
#$56q~	4	+long, +bk, -hi, -rhotacized
#12368	4	+long, -rnd, -hi, -nasal
$15@EV	4	-diphthong, -lo, -hi, -rhotacized
018Ec{	4	-diphthong, -bk, -hi, -reduced
01@Ec{	4	-diphthong, -bk, -hi, -rhotacized
178EIi	4	-diphthong, -bk, -lo, -reduced
#$35QV	4	-diphthong, +bk, -hi, -nasal
1@EIVi	4	-diphthong, -rnd, -lo, -rhotacized
#$1358	4	-diphthong, +long, -hi, -nasal
#$5qu~	4	-diphthong, +long, +bk, -rhotacized
#$359u	4	-diphthong, +long, +bk, -nasal
#01iq~	4	-diphthong, +long, -rnd, -rhotacized
#1378i	4	-diphthong, +long, -rnd, -nasal
1248E{	4	-reduced, -bk, -hi, -nasal
124EIi	4	-reduced, -bk, -lo, -rhotacized
012Ec{	5	-reduced, -rnd, -bk, -hi, -rhotacized
EIQUV{	3	-reduced, -long, -nasal
124@E{	4	-rhotacized, -bk, -hi, -nasal
#$56QV	4	-rhotacized, +bk, -hi, -nasal
1@EIi{	4	-rhotacized, -diphthong, -bk, -nasal
#$15iu	4	-rhotacized, -diphthong, +long, -nasal
12EIi{	5	-rhotacized, -reduced, -rnd, -bk, -nasal
#1EQV{	6	-rhotacized, -reduced, -diphthong, -rnd, -hi, -nasal
DSTZsz	2	+coronal, +continuant
#0Qcq{~	1	+lo
bfmprvw	1	+labial
dlnrstz	1	+alveolar
Njlmnrw	1	+sonorant
012478i	2	-bk, +long
018@Ec{	3	-bk, -hi, -diphthong
1248@E{	3	-bk, -hi, -nasal
178@EIi	3	-bk, -lo, -diphthong
124@EIi	3	-bk, -lo, -rhotacized
#36QVq~	2	+bk, -rnd
#$356q~	3	+bk, -hi, +long
#$356QV	3	+bk, -hi, -nasal
$359UVu	3	+bk, -lo, -diphthong
@EIQVc{	2	-rnd, -long
123678i	3	-rnd, -lo, +long
12368EV	4	-rnd, -lo, -hi, -reduced
0128Ec{	4	-rnd, -bk, -hi, -reduced
012@Ec{	4	-rnd, -bk, -hi, -rhotacized
1278EIi	4	-rnd, -bk, -lo, -reduced
EIQUVc{	2	-long, -reduced
@EIQUV{	2	-long, -nasal
#$56qu~	3	+long, +bk, -rhotacized
#$3569u	3	+long, +bk, -nasal
#0138q~	4	+long, -rnd, -hi, -diphthong
#0126q~	4	+long, -rnd, -hi, -rhotacized
$1358EV	4	-diphthong, -lo, -hi, -reduced
#$5QVq~	4	-diphthong, +bk, -hi, -rhotacized
#$015q~	4	-diphthong, +long, -hi, -rhotacized
0124Ec{	4	-reduced, -bk, -hi, -rhotacized
126EIVi	4	-reduced, -rnd, -lo, -rhotacized
01EIci{	4	-reduced, -diphthong, -bk, -rhotacized
178EIi{	4	-reduced, -diphthong, -bk, -nasal
12@EIi{	4	-rhotacized, -rnd, -bk, -nasal
#$12456	4	-rhotacized, +long, -hi, -nasal
#$5QUVu	4	-rhotacized, -diphthong, +bk, -nasal
#1@EQV{	5	-rhotacized, -diphthong, -rnd, -hi, -nasal
124EIi{	4	-rhotacized, -reduced, -bk, -nasal
N_bdgmn	2	+stop, +voice
@EIQUVc{	1	-long
$3569UVu	2	-lo, +bk
12368@EV	3	-lo, -hi, -rnd
$1234568	3	-lo, -hi, +long
$1358@EV	3	-lo, -hi, -diphthong
0128@Ec{	3	-bk, -hi, -rnd
01248Ec{	3	-bk, -hi, -reduced
0124@Ec{	3	-bk, -hi, -rhotacized
1278@EIi	3	-bk, -lo, -rnd
12478EIi	3	-bk, -lo, -reduced
#$35QVq~	3	+bk, -hi, -diphthong
#$56QVq~	3	+bk, -hi, -rhotacized
126@EIVi	3	-rnd, -lo, -rhotacized
$12456iu	3	+long, -lo, -rhotacized
#$359qu~	3	+long, +bk, -diphthong
#0126iq~	3	+long, -rnd, -rhotacized
#123678i	3	+long, -rnd, -nasal
01@EIci{	3	-diphthong, -bk, -rhotacized
178@EIi{	3	-diphthong, -bk, -nasal
1378EIVi	4	-diphthong, -rnd, -lo, -reduced
$12456EV	4	-reduced, -lo, -hi, -rhotacized
012EIci{	4	-reduced, -rnd, -bk, -rhotacized
1278EIi{	4	-reduced, -rnd, -bk, -nasal
#138EQV{	5	-reduced, -diphthong, -rnd, -hi, -nasal
124@EIi{	3	-rhotacized, -bk, -nasal
#$56QUVu	3	-rhotacized, +bk, -nasal
#126EQV{	5	-rhotacized, -reduced, -rnd, -hi, -nasal
#$15EQV{	5	-rhotacized, -reduced, -diphthong, -hi, -nasal
#1EIQVi{	5	-rhotacized, -reduced, -diphthong, -rnd, -nasal
DZ_dlnrz	3	+coronal, +consonantal, +voice
J_bdgkpt	2	+obstruent, +stop
DZ_bdgvz	2	+obstruent, +voice
DSTZfhsvz	1	+continuant
JSTfhkpst	1	+voiceless
01248@Ec{	2	-hi, -bk
#$356QVq~	2	-hi, +bk
12478@EIi	2	-lo, -bk
$12456@EV	3	-lo, -hi, -rhotacized
#$3569qu~	2	+bk, +long
#012368q~	3	-rnd, -hi, +long
1378@EIVi	3	-rnd, -lo, -diphthong
012@EIci{	3	-rnd, -bk, -rhotacized
1278@EIi{	3	-rnd, -bk, -nasal
#$01358q~	3	+long, -hi, -diphthong
#$1234568	3	+long, -hi, -nasal
$135789iu	3	+long, -lo, -diphthong
#01378iq~	3	+long, -rnd, -diphthong
0178EIci{	3	-diphthong, -bk, -reduced
#$5QUVqu~	3	-diphthong, +bk, -rhotacized
#$359QUVu	3	-diphthong, +bk, -nasal
#138@EQV{	4	-diphthong, -rnd, -hi, -nasal
#$015iqu~	3	-diphthong, +long, -rhotacized
0124EIci{	3	-reduced, -bk, -rhotacized
12478EIi{	3	-reduced, -bk, -nasal
$15EIUViu	4	-reduced, -diphthong, -lo, -rhotacized
#126@EQV{	4	-rhotacized, -rnd, -hi, -nasal
#$12456iu	3	-rhotacized, +long, -nasal
#$15@EQV{	4	-rhotacized, -diphthong, -hi, -nasal
#1@EIQVi{	4	-rhotacized, -diphthong, -rnd, -nasal
DZ_djlnrz	2	+coronal, +voice
$1234568EV	3	-lo, -hi, -reduced
0178@EIci{	2	-bk, -diphthong
0124@EIci{	2	-bk, -rhotacized
12478@EIi{	2	-bk, -nasal
#$56QUVqu~	2	+bk, -rhotacized
#$3569QUVu	2	+bk, -nasal
123678EIVi	3	-rnd, -lo, -reduced
01278EIci{	3	-rnd, -bk, -reduced
#$012456q~	3	+long, -hi, -rhotacized
$15@EIUViu	3	-diphthong, -lo, -rhotacized
#$135789iu	3	-diphthong, +long, -nasal
#12368EQV{	4	-reduced, -rnd, -hi, -nasal
#$1358EQV{	4	-reduced, -diphthong, -hi, -nasal
#01EQVcq{~	5	-reduced, -diphthong, -rnd, -hi, -rhotacized
#126EIQVi{	4	-rhotacized, -reduced, -rnd, -nasal
DJSTZ_dstz	2	+coronal, +obstruent
JN_bdgkmnpt	1	+stop
$1234568@EV	2	-hi, -lo
123678@EIVi	2	-lo, -rnd
01278@EIci{	2	-bk, -rnd
012478EIci{	2	-bk, -reduced
#$359QUVqu~	2	+bk, -diphthong
#0123678iq~	2	-rnd, +long
#12368@EQV{	3	-rnd, -hi, -nasal
#$1358@EQV{	3	-diphthong, -hi, -nasal
#01@EQVcq{~	4	-diphthong, -rnd, -hi, -rhotacized
#1378EIQVi{	4	-reduced, -diphthong, -rnd, -nasal
#126@EIQVi{	3	-rhotacized, -rnd, -nasal
#$12456EQV{	4	-rhotacized, -reduced, -hi, -nasal
012478@EIci{	1	-bk
#$3569QUVqu~	1	+bk
#$01234568q~	2	-hi, +long
$123456789iu	2	-lo, +long
#$012456iqu~	2	+long, -rhotacized
#1378@EIQVi{	3	-diphthong, -rnd, -nasal
#0138EQVcq{~	4	-diphthong, -rnd, -hi, -reduced
$12456EIUViu	3	-reduced, -lo, -rhotacized
#0126EQVcq{~	4	-reduced, -rnd, -hi, -rhotacized
#$015EQVcq{~	4	-reduced, -diphthong, -hi, -rhotacized
#01EIQVciq{~	4	-reduced, -diphthong, -rnd, -rhotacized
#$12456@EQV{	3	-rhotacized, -hi, -nasal
#$15EIQUViu{	4	-rhotacized, -reduced, -diphthong, -nasal
DJSTZ_dlnrstz	2	+consonantal, +coronal
DNZ_bdglmnrvz	2	+consonantal, +voice
$12456@EIUViu	2	-lo, -rhotacized
#0138@EQVcq{~	3	-rnd, -hi, -diphthong
#0126@EQVcq{~	3	-rnd, -hi, -rhotacized
#$0135789iqu~	2	+long, -diphthong
#$123456789iu	2	+long, -nasal
#$015@EQVcq{~	3	-diphthong, -hi, -rhotacized
$135789EIUViu	3	-diphthong, -lo, -reduced
#01@EIQVciq{~	3	-diphthong, -rnd, -rhotacized
#$1234568EQV{	3	-reduced, -hi, -nasal
#123678EIQVi{	3	-reduced, -rnd, -nasal
#$15@EIQUViu{	3	-rhotacized, -diphthong, -nasal
DJSTZ_djlnrstz	1	+coronal
#$1234568@EQV{	2	-hi, -nasal
$135789@EIUViu	2	-lo, -diphthong
#123678@EIQVi{	2	-rnd, -nasal
#012368EQVcq{~	3	-rnd, -hi, -reduced
#$01358EQVcq{~	3	-diphthong, -hi, -reduced
#0126EIQVciq{~	3	-reduced, -rnd, -rhotacized
DNZ_bdgjlmnrvwz	1	+voice
#012368@EQVcq{~	2	-hi, -rnd
#$01358@EQVcq{~	2	-hi, -diphthong
#0126@EIQVciq{~	2	-rnd, -rhotacized
#01378EIQVciq{~	3	-diphthong, -rnd, -reduced
#$012456EQVcq{~	3	-reduced, -hi, -rhotacized
#$12456EIQUViu{	3	-rhotacized, -reduced, -nasal
#$0123456789iqu~	1	+long
#$012456@EQVcq{~	2	-hi, -rhotacized
$123456789EIUViu	2	-lo, -reduced
#01378@EIQVciq{~	2	-rnd, -diphthong
#$015EIQUVciqu{~	3	-reduced, -diphthong, -rhotacized
#$135789EIQUViu{	3	-reduced, -diphthong, -nasal
#$12456@EIQUViu{	2	-rhotacized, -nasal
$123456789@EIUViu	1	-lo
DJSTZ_bdfghkpstvz	1	+obstruent
#$01234568EQVcq{~	2	-hi, -reduced
#0123678EIQVciq{~	2	-rnd, -reduced
#$015@EIQUVciqu{~	2	-diphthong, -rhotacized
#$135789@EIQUViu{	2	-diphthong, -nasal
#$01234568@EQVcq{~	1	-hi
#0123678@EIQVciq{~	1	-rnd
#$012456EIQUVciqu{~	2	-reduced, -rhotacized
#$123456789EIQUViu{	2	-reduced, -nasal
#$012456@EIQUVciqu{~	1	-rhotacized
#$123456789@EIQUViu{	1	-nasal
#$0135789EIQUVciqu{~	2	-diphthong, -reduced
#$0135789@EIQUVciqu{~	1	-diphthong
DJNSTZ_bdfghklmnprstvz	1	+consonantal
#$0123456789EIQUVciqu{~	1	-reduced
DJNSTZ_bdfghjklmnprstvwz	1	-syllabic
#$0123456789@EIQUVciqu{~	1	+syllabic
#$0123456789@EIQUVcijquw{~	1	-consonantal
#$0123456789@DEIJNQSTUVZ_bcdfghijklmnpqrstuvwz{~	0	+seg
